name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" >> .env
          echo "${{ secrets.OPENAI_API_KEY }}" >> .env

      # Set up Python environment
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      # Create and activate Python virtual environment
      - name: Set up Python virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Start or restart BackendAPI using PM2
      - name: Start or Restart BackendAPI
        run: |
          pm2 start index.js --name BackendAPI || pm2 restart BackendAPI --update-env